In [ ]:
#---------Mice problem----------


In [ ]:
# In this problem we have a total of 7 different categories
# in class,That defines different types of protein in the cortex of 
# Mice and by given attributes we have to conclude which type protein it 
# is.
# We have used SVC that is support vector classifier that is used
# for classification purpose and as this dataset has many attributes
# SVM is a great choice for this types of problem where we have must 
# attributes that help us to classify.


In [1]:
#importing libraries

import pandas as pd
import numpy as np


In [2]:
#importing and cleaning the dataset

dataset = pd.read_csv('Downloads/Data_Cortex_Nuclear.csv')
dataset = dataset.dropna()
dataset.head()

MouseID  DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N  \
75  3415_1  0.649781  0.828696  0.405862  2.921435  5.167979  0.207174   
76  3415_2  0.616481  0.841974  0.388584  2.862575  5.194163  0.223433   
77  3415_3  0.637424  0.852882  0.400561  2.968155  5.350820  0.208790   
78  3415_4  0.576815  0.755390  0.348346  2.624901  4.727509  0.205892   
79  3415_5  0.542545  0.757917  0.350051  2.634509  4.735602  0.210526   

     pBRAF_N  pCAMKII_N   pCREB_N   ...     pCFOS_N     SYP_N  H3AcK18_N  \
75  0.176640   3.728084  0.239283   ...    0.129363  0.486912   0.125152   
76  0.167725   3.648240  0.221030   ...    0.143084  0.467833   0.112857   
77  0.173261   3.814545  0.222300   ...    0.147673  0.462501   0.116433   
78  0.161192   3.778530  0.194153   ...    0.121290  0.479110   0.102831   
79  0.165671   3.871971  0.194297   ...    0.142617  0.438354   0.110614   

      EGR1_N  H3MeK4_N    CaNA_N  Genotype  Treatment  Behavior   class  
75  0.146865  0.143517  1.627181   Control  Memantine       C/S  c-CS-m  
76  0.161132  0.145719  1.562096   Control  Memantine       C/S  c-CS-m  
77  0.160594  0.142879  1.571868   Control  Memantine       C/S  c-CS-m  
78  0.144238  0.141681  1.646608   Control  Memantine       C/S  c-CS-m  
79  0.155667  0.146408  1.607631   Control  Memantine       C/S  c-CS-m  

[5 rows x 82 columns]

In [3]:
#total columns in the dataset

dataset.columns

Index(['MouseID', 'DYRK1A_N', 'ITSN1_N', 'BDNF_N', 'NR1_N', 'NR2A_N', 'pAKT_N',
       'pBRAF_N', 'pCAMKII_N', 'pCREB_N', 'pELK_N', 'pERK_N', 'pJNK_N',
       'PKCA_N', 'pMEK_N', 'pNR1_N', 'pNR2A_N', 'pNR2B_N', 'pPKCAB_N',
       'pRSK_N', 'AKT_N', 'BRAF_N', 'CAMKII_N', 'CREB_N', 'ELK_N', 'ERK_N',
       'GSK3B_N', 'JNK_N', 'MEK_N', 'TRKA_N', 'RSK_N', 'APP_N', 'Bcatenin_N',
       'SOD1_N', 'MTOR_N', 'P38_N', 'pMTOR_N', 'DSCR1_N', 'AMPKA_N', 'NR2B_N',
       'pNUMB_N', 'RAPTOR_N', 'TIAM1_N', 'pP70S6_N', 'NUMB_N', 'P70S6_N',
       'pGSK3B_N', 'pPKCG_N', 'CDK5_N', 'S6_N', 'ADARB1_N', 'AcetylH3K9_N',
       'RRP1_N', 'BAX_N', 'ARC_N', 'ERBB4_N', 'nNOS_N', 'Tau_N', 'GFAP_N',
       'GluR3_N', 'GluR4_N', 'IL1B_N', 'P3525_N', 'pCASP9_N', 'PSD95_N',
       'SNCA_N', 'Ubiquitin_N', 'pGSK3B_Tyr216_N', 'SHH_N', 'BAD_N', 'BCL2_N',
       'pS6_N', 'pCFOS_N', 'SYP_N', 'H3AcK18_N', 'EGR1_N', 'H3MeK4_N',
       'CaNA_N', 'Genotype', 'Treatment', 'Behavior', 'class'],
      dtype='object')

In [4]:
#using labelencoder to encode the strings
# that is the unique strings in the columns 

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
dataset['Genotype'] = enc.fit_transform(dataset['Genotype'])

In [5]:
dataset['Treatment'] = enc.fit_transform(dataset['Treatment'])

In [6]:
dataset['Behavior'] = enc.fit_transform(dataset['Behavior'])

In [7]:
dataset['class'] = enc.fit_transform(dataset['class'])

In [8]:
dataset.head()

MouseID  DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N  \
75  3415_1  0.649781  0.828696  0.405862  2.921435  5.167979  0.207174   
76  3415_2  0.616481  0.841974  0.388584  2.862575  5.194163  0.223433   
77  3415_3  0.637424  0.852882  0.400561  2.968155  5.350820  0.208790   
78  3415_4  0.576815  0.755390  0.348346  2.624901  4.727509  0.205892   
79  3415_5  0.542545  0.757917  0.350051  2.634509  4.735602  0.210526   

     pBRAF_N  pCAMKII_N   pCREB_N  ...     pCFOS_N     SYP_N  H3AcK18_N  \
75  0.176640   3.728084  0.239283  ...    0.129363  0.486912   0.125152   
76  0.167725   3.648240  0.221030  ...    0.143084  0.467833   0.112857   
77  0.173261   3.814545  0.222300  ...    0.147673  0.462501   0.116433   
78  0.161192   3.778530  0.194153  ...    0.121290  0.479110   0.102831   
79  0.165671   3.871971  0.194297  ...    0.142617  0.438354   0.110614   

      EGR1_N  H3MeK4_N    CaNA_N  Genotype  Treatment  Behavior  class  
75  0.146865  0.143517  1.627181         0          0         0      0  
76  0.161132  0.145719  1.562096         0          0         0      0  
77  0.160594  0.142879  1.571868         0          0         0      0  
78  0.144238  0.141681  1.646608         0          0         0      0  
79  0.155667  0.146408  1.607631         0          0         0      0  

[5 rows x 82 columns]

In [9]:
# Getting X_data and printing instances of X_data

X_data = dataset.iloc[:,1:-1].values
X_data[0:2]

array([[0.64978128, 0.82869641, 0.40586177, 2.92143482, 5.167979  ,
        0.2071741 , 0.17664042, 3.72808399, 0.23928259, 1.66657918,
        0.96946632, 0.32125984, 0.40656168, 0.25529309, 1.05634296,
        1.09930009, 1.92528434, 2.23167104, 0.42685914, 0.87322835,
        0.5127734 , 0.3432196 , 0.16762905, 1.85275591, 3.36649169,
        1.50367454, 0.24601925, 0.30542432, 0.85100612, 0.16517935,
        0.44155731, 2.57821522, 0.34085739, 0.48766404, 0.40104987,
        0.78136483, 0.53403325, 0.43184602, 0.61802275, 0.36141732,
        0.32195976, 0.42729659, 0.25205599, 0.24208604, 1.06118101,
        0.16375812, 1.8623681 , 0.32117492, 0.54104099, 2.15954748,
        0.1346388 , 0.15817776, 0.19612419, 0.13200081, 0.16112013,
        0.21098823, 0.21037946, 0.12814529, 0.29246144, 0.1525974 ,
        0.52724229, 0.34806209, 1.68755073, 2.43658685, 0.16817167,
        1.13915382, 0.98777395, 0.23975244, 0.13905235, 0.11292614,
        0.13200081, 0.12936282, 0.48691153, 0.12

In [10]:
#Getting Y_data

Y_data = dataset['class'].values
Y_data[0:5]

array([0, 0, 0, 0, 0])

In [11]:
#Getting the unique classes in Y_data and the no of instances of each 
# class

unique , counts = np.unique(Y_data,return_counts=True)
print(unique,counts)

[0 1 2 3 4 5 6 7] [45 75 60 75 90 75 60 72]


In [12]:
#scaling the inputs using StandardScaler

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_data = scaler.fit_transform(X_data)
X_data[0:2]

array([[ 1.43670714,  1.12612827,  1.70538327,  1.70323178,  1.49995771,
        -0.45054164,  0.04754992,  0.07722825,  0.86257169,  0.76181626,
         1.86520493,  0.27687724,  1.55670026, -0.22285567,  1.85707195,
         1.87867141,  1.30736555,  1.18843304, -0.36085459,  1.48850415,
         1.18722443, -0.10408608, -0.21598971,  1.7790818 ,  1.33175035,
         1.55572493,  0.33806607,  0.82236687,  1.26626099,  0.18290735,
         0.53605   ,  0.94474418, -0.6642671 ,  0.70808321, -0.06404139,
         0.28060011, -0.27315372,  1.23842171,  0.75159634,  0.24542234,
         0.42693232,  0.24194543, -0.93608574,  1.7651144 ,  0.54189096,
         0.14725209,  0.08686206,  0.61658668,  0.66688471,  2.52795364,
        -0.45302747, -0.1278299 ,  0.8334766 ,  0.83764337,  0.35303447,
         1.01215806,  0.09289556,  0.92587142,  2.07832657,  1.31284564,
         0.00324428,  1.90741363,  0.43557705,  0.87579814,  0.52423411,
        -0.47365992,  1.46125019,  0.41572273, -0.5

In [13]:
# splitting data into training and testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_data,Y_data,test_size=0.3)

In [14]:
#Getting our classifier

from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
#using cross_val_score for checking accuracy on different folds

from sklearn.model_selection import cross_val_score
results = cross_val_score(classifier,x_test,y_test,cv=5)
print(results)

[0.89189189 0.88571429 0.96969697 1.         0.96551724]


In [16]:
# in the best case scenario we got a accuracy score of 100 %.

In [17]:
#finally printing the accuracy on training set

classifier.score(x_train,y_train)

1.0